# Generated by Django 5.1.1 on 2024-10-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='horas',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
