# Generated by Django 5.1.1 on 2024-10-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_horas_worksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cbarra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
