# Generated by Django 5.1.1 on 2024-11-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_barcode_image_registroasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cbarra',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
