# Generated by Django 5.1.1 on 2024-11-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_cbarra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cbarra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
