# Generated by Django 5.1.1 on 2024-11-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_customuser_cbarra'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
