# Generated by Django 5.1.1 on 2024-11-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_registroasistencia_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salario_por_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
